# Generated by Django 2.1.7 on 2019-03-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploader', '0003_auto_20190327_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='files/', verbose_name='Archivo'),
        ),
    ]
