# Generated by Django 2.1.7 on 2019-04-02 02:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploader', '0004_auto_20190329_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='Archivo'),
        ),
    ]
