# Generated by Django 2.1.7 on 2019-04-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploader', '0005_auto_20190402_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='files/', verbose_name='Archivo'),
        ),
    ]
