# Generated by Django 2.1.7 on 2019-05-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploader', '0007_auto_20190525_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='lat_col',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='lon_col',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
